export default {
  login: 'lucianomuniz',
  id: 13963676,
  node_id: 'MDQ6VXNlcjEzOTYzNjc2',
  avatar_url: 'https://avatars.githubusercontent.com/u/13963676?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/lucianomuniz',
  html_url: 'https://github.com/lucianomuniz',
  followers_url: 'https://api.github.com/users/lucianomuniz/followers',
  following_url:
    'https://api.github.com/users/lucianomuniz/following{/other_user}',
  gists_url: 'https://api.github.com/users/lucianomuniz/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/lucianomuniz/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/lucianomuniz/subscriptions',
  organizations_url: 'https://api.github.com/users/lucianomuniz/orgs',
  repos_url: 'https://api.github.com/users/lucianomuniz/repos',
  events_url: 'https://api.github.com/users/lucianomuniz/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/lucianomuniz/received_events',
  type: 'User',
  site_admin: false,
  name: 'Luciano Muniz',
  company: null,
  blog: '',
  location: 'Brazil',
  email: null,
  hireable: null,
  bio: 'Web Software Developer | NodeJS | React | Full-Stack JavaScript',
  twitter_username: null,
  public_repos: 38,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: '2015-08-25T13:30:32Z',
  updated_at: '2022-06-02T19:23:44Z',
};
